### PR TITLE
Add example of fast simulation of a detector.

### PR DESCRIPTION
**Pull request by kresan**

### CODE REVIEW

**Comment by sawenzel** [comment]
This is very nice development! 

Just one worry: Since you modify FairStack, I am wondering if you explicitely make sure that no client inheriting from FairStack is affected by these changes?

**Comment by MohammadAlTurany** [comment]
Hi @sawenzel 

The old functionality is preserved, the only change for the users who do not use this extra functionality is the one extra test in PopPrimaryForTracking(Int_t iPrim). So it should not effect you. Anyway please test it and let us know if you see any side effects.

**Comment by sawenzel** [comment]
Ok thanks. This is probably ok. But of course since these functions are virtual some of this functionality might be unintentionally lost in client code if they override ...

**Comment by ktf** [comment]
This breaks the compilation of O2. See for example:

https://ali-ci.cern.ch/repo/logs/AliceO2Group/AliceO2/1676/c989c29c724b6a15f0684bcf2721b11423670243/build_O2_o2-dev-fairroot/fullLog.txt

Could it be fixed? Thanks.

**Comment by ktf** [comment]
Actual error in case you do not have a CERN account:

```bash
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-8/bin/c++  -DFairFastSim_EXPORTS -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/logger -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/fairtools -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/event -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/steer -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/source -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sink -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/geobase -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/parbase -I/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim/fastsim -isystem /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/FairLogger/v1.2.0-7/include -isystem /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include -isystem /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.68.0-9/include -isystem /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GEANT4/v10.4.2-4/include/Geant4 -isystem /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GEANT4_VMC/v3-6-p1-52/include/geant4vmc -isystem /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GEANT4_VMC/v3-6-p1-52/include/g4root -fPIC -O2 -std=c++17 -fdiagnostics-color=always -O2 -g -Wshadow -fPIC   -std=c++11 -MD -MT base/sim/fastsim/CMakeFiles/FairFastSim.dir/FairFastSimModel.cxx.o -MF base/sim/fastsim/CMakeFiles/FairFastSim.dir/FairFastSimModel.cxx.o.d -o base/sim/fastsim/CMakeFiles/FairFastSim.dir/FairFastSimModel.cxx.o -c /mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim/fastsim/FairFastSimModel.cxx
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:28:0,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TCollection.h:29,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TSeqCollection.h:25,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TObjArray.h:25,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TClonesArray.h:27,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim/FairGenericStack.h:23,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim/fastsim/FairFastSimModel.cxx:20:
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/ROOT/RStringView.hxx:67:17: error: expected type-specifier
        operator std::string_view() const { return std::string_view(fData,fLength); }
                 ^~~
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TCollection.h:29:0,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TSeqCollection.h:25,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TObjArray.h:25,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TClonesArray.h:27,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim/FairGenericStack.h:23,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim/fastsim/FairFastSimModel.cxx:20:
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:110:13: error: expected type-specifier
    operator std::string_view() const { return std::string_view(Data(),fExtent); }
             ^~~
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:275:23: error: 'string_view' in namespace 'std' does not name a type
    TString(const std::string_view &sub);
                       ^~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:312:37: error: 'string_view' in namespace 'std' does not name a type
    TString    &operator=(const std::string_view &s);
                                     ^~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:439:9: error: 'string_view' in namespace 'std' does not name a type
    std::string_view View() const { return std::string_view(GetPointer(),Length()); }
         ^~~~~~~~~~~
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TCollection.h:29:0,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TSeqCollection.h:25,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TObjArray.h:25,
                 from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TClonesArray.h:27,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim/FairGenericStack.h:23,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/FairRoot/build_O2_o2-dev-fairroot/0/base/sim/fastsim/FairFastSimModel.cxx:20:
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:834:53: error: 'string_view' in namespace 'std' does not name a type
 inline Bool_t operator==(const char *s1, const std::string_view &s2)
                                                     ^~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:834:68: error: 'Bool_t operator==(const char*, const int&)' must have an argument of class or enumerated type
 inline Bool_t operator==(const char *s1, const std::string_view &s2)
                                                                    ^
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:839:37: error: 'string_view' in namespace 'std' does not name a type
 inline Bool_t operator==(const std::string_view &s1, const char *s2)
                                     ^~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:839:68: error: 'Bool_t operator==(const int&, const char*)' must have an argument of class or enumerated type
 inline Bool_t operator==(const std::string_view &s1, const char *s2)
                                                                    ^
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-14-04-52/include/TString.h:852:37: error: 'string_view' in namespace 'std' does not name a type
   std::string printValue(const std::string_view* val);
                                     ^~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by karabowi** [comment]
It seems that the problem is caused by wrongly specified cxx_flags. Namely the command uses "c++ -std=c++17 -std=c++11", which ultimately takes c++11. This causes problem with the c++17 standard used to compile root. I do not see any place where I set the flag in the fastSim CMake.
Do you start from a fresh installation in your sandbox? If not, can you?
Since when are you using c++17 to build root?

**Comment by sawenzel** [comment]
I agree. I think we actually compile with C++11 instead of C++17.

**Comment by ktf** [comment]
You mean FairRoot? Because in O2 we have for sure C++17 code.

**Comment by sawenzel** [comment]
For sure something overrides C++17 to C++11 for the new classes (FastSim). The compile database tells me this:
`t  -fPIC -O2 -std=c++17 -O2 -g -Wshadow -fPIC   -std=c++11 -o CMakeFiles/FairFastSim.dir/FairFastSimulation.cxx.o -c /home/sandro/alisw/sw/SOURCES/FairRoot/0/0/base/sim/fastsim/FairFastSimulation.cxx",`

This means that the system to set the standard via global CXX_FLAGS is not bulletproof. Please find a fix on our side here: https://github.com/alisw/alidist/pull/1497

**Pull request merged**
