### PR TITLE
Drop deprecated FairRootManager::GetOut{File,Tree}

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
See-Also: 1da8249a8fbf07380bb7b2f5017c809a61cf2fe9

---

Checklist:

* [X] Rebased against `dev` branch
* [X] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [X] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Review by dennisklein — APPROVED** [review]

**Comment by DanielWielanek** [comment]
Hi, I have one comment concerning this commit. Do we have another way of getting the name of the inputfile.
I used this method to get name of the file with analyzed data.

**Comment by dennisklein** [comment]
> Hi, I have one comment concerning this commit. Do we have another way of getting the name of the inputfile. I used this method to get name of the file with analyzed data.

e.g.
```cpp
auto sink = GetSink();
assert(sink->GetSinkType() == kFILESINK);
auto rootFileSink = static_cast<FairRootFileSink*>(sink);
auto file = rootFileSink->GetRootFile();
auto tree = rootFileSink->GetOutTree();
```

**Review by fuhlig1 — APPROVED** [review]
Fine with me

**Comment by fuhlig1** [comment]
From my side the PR can be merged any time.

**Review by karabowi — APPROVED** [review]
The GetOutFile method is still used by Panda and CBM, but there was enough time to change that.

**Pull request merged**
