### PR TITLE
refactor: Avoid FairGeoLoader::Instance()

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
Instead add a few GetGeometryLoader() getters and use them. Also let FairModule know to which FairRunSim it belongs.

---

Checklist:

* [X] Followed the [Contributing Guidelines](https://github.com/FairRootGroup/FairRoot/blob/dev/CONTRIBUTING.md)

### CODE REVIEW

**Review by dennisklein — COMMENTED** [review]
What's your idea behind the `friend class FairRunSim` + direct member access vs just a public setter (and/or ctor overload)?

**Comment by ChristianTackeGSI** [comment]
> What's your idea behind the `friend class FairRunSim` + direct member access vs just a public setter (and/or ctor overload)?

My general idea: Setting fRunSim is (currently) not intended as a public inteface.

> Thinking also about unit testability.

Good point. It would be good for tests to be able to set a moch RunSim there…

So, I am going to add a member function with a "for internal use" description.

**Review by dennisklein — COMMENTED** [review]
The remaining thought I have, is, if the association of a `FairModule` to a `FairRunSim` is general enough. In other words, are `FairModule`s only used in simulation and never in other run types?

**Comment by ChristianTackeGSI** [comment]
> The remaining thought I have, is, if the association of a `FairModule` to a `FairRunSim` is general enough. In other words, are `FairModule`s only used in simulation and never in other run types?

@karabowi, @fuhlig1: Can you please comment on this?

**Review by dennisklein — APPROVED** [review]
Chatted with @karabowi about this and we concluded this is fine. Does not break any API anyhow and if we discover this needs to be more generic, we can then still move it to `FairRun` or somewhere else.

**Pull request merged**
