### PR TITLE
FairRunSim: Improve memory handling

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
* Do not leak `fLoaderName`
* Use `unique_ptr` for `fApp`, `fGen,` `fMCEvHead`
* Drop unneeded `fMapName`

---

Checklist:

* [X] Followed the [Contributing Guidelines](https://github.com/FairRootGroup/FairRoot/blob/dev/CONTRIBUTING.md)

### CODE REVIEW

**Review by karabowi — APPROVED** [review]
Tested with PandaRoot. Requires some changes in PndMasterRunSim, as currently it assumes fGen to be protected pointer to FairPrimaryGenerator.
Requested review from Florian (CBM) and Dima (R3B).

**Comment by ChristianTackeGSI** [comment]
Would it help to keep the new `std::unique_ptr` as a protected member variable instead of a private one?

**Comment by karabowi** [comment]
Replaced by PR #1331.

**Comment by ChristianTackeGSI** [comment]
#1331 has parts of what was here. Thanks for already merging that.

The core parts of memory handling (and the question about what to do with `fGen` (keep it as protected?) is also still open.

I have rebased it.

**Comment by ChristianTackeGSI** [comment]
Okay, re-opening isn't possible, if one force-pushes before re-opening.

So created a new one: #1332

**Pull request closed without merging**
