### PR TITLE
V18.6 patches

### PR DESCRIPTION
**Pull request by fuhlig1**
Add missing streamer which allows to read/write the data format required by the FairAlignmentHandler from/to file.

Fix linking problem on macosx12.
---

Checklist:

* [ x] Rebased against `apr21_patches` branch
* [ x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [ x] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by fuhlig1** [comment]
Should the code really changed in the way clang wants to have it?

**Comment by dennisklein** [comment]
> Should the code really changed in the way clang wants to have it?

Well, thats the problem with format tools, they do things mostly right 95% of times. In this case, I agree, that the proposed change is rather off. Do you want to figure out how to make an exception and the check happy again? Or do you want someone else to do it?

**Comment by dennisklein** [comment]
Is there any specific reason to base against `v18.6_patches` branch?

**Comment by fuhlig1** [comment]
> Well, thats the problem with format tools, they do things right 95% of times only. In this case, I agree, that the proposed change is rather off. Do you want to figure out how to make an exception and the check happy again? Or do you want someone else to do it?

If it is okay to do 

```
/* clang-format off */
/* clang-format on */
```

around the problematic code I will do it.

**Comment by fuhlig1** [comment]
> Is there any specific reason to base against `v18.6_patches` branch?

Yes. Since the changes mostly touch the build system which has changed in dev I decided to base the PR against the patch branch for simplicity.  Because some manual work is needed to port the changes from one branch to the other I did the PR against the branch I used for testing.

Imeans manual work to port the changes from one branch to the other

**Comment by fuhlig1** [comment]
Please don't merge yet. I have found another problem with the FairAlignmentHandler which I currently discuss with the original author of the code.

**Comment by fuhlig1** [comment]
> Is there any specific reason to base against `v18.6_patches` branch?

With #1125 there is now also a PR which adds the changes to the alignment in the dev branch. The change to fix the linking on macosx 12 isn't needed in the dev branch.

**Comment by fuhlig1** [comment]
@dennisklein, 

one unrelated technical question. How can I mark the PR as draft. I was looking for the feature when I send my "please don't merge comment" but did not find it.

**Comment by fuhlig1** [comment]
Okay, now I found it. :grinning:

**Pull request merged**
