### PR TITLE
Remove GetObject from FairRunAnaProof

### PR DESCRIPTION
**Pull request by karabowi**
Reworked according to FairRunAna.

Addresses point 1 in issue #1346.

---

Checklist:

* [x] Followed the [Contributing Guidelines](https://github.com/FairRootGroup/FairRoot/blob/dev/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ChristianTackeGSI** [comment]
This generally looks good to me. It feels like a good thing.

But as I don't fully understand this whole block yet, I don't feel competent enough to leave a full review/approval.

Read this as: No veto by me.

**Comment by ChristianTackeGSI** [comment]
If nobody else will approve this until the end of the week, I am happy to leave an approval then. But let's first hope for someone else to take another look?

**Review by ChristianTackeGSI — APPROVED** [review]
Let's just do it. Yet another instance of GetObject going away!

I think, you need to rebase. I'll re-approve then.

**Comment by karabowi** [comment]
Done!

**Review by ChristianTackeGSI — APPROVED** [review]

**Comment by ChristianTackeGSI** [comment]
I fear, we have to do the same in FairRunOnline?
https://github.com/FairRootGroup/FairRoot/blob/12f519f8054d50d0d0edc345878f93a8b76a9699/fairroot/online/steer/FairRunOnline.cxx#L221
I have added that to #1346

**Pull request merged**
