### PR TITLE
Do not build FastSim module if Geant4 not found

### PR DESCRIPTION
**Pull request by sawenzel**
This is useful for clients using FairRoot without
the simulation components.

Relates to https://github.com/alisw/alidist/pull/1776

### CODE REVIEW

**Comment by fuhlig1** [comment]
Could you please check if pull request #912 solves your problem. Since it solves more issues like the one you found I prefer to merge this one.

**Comment by sawenzel** [comment]
Yes. Looks like this will also solve the problem. Do you plan to merge the other one soon?

**Comment by fuhlig1** [comment]
It should have been already merged but I didn't find the time to test it and up to now it was not urgent. I will try to do it tomorrow.

**Comment by fuhlig1** [comment]
Fixed with 6af7e848585ce720e96a01d5565b1bd5e3884430

**Pull request closed without merging**
