### PR TITLE
Series of small bugfixes

### PR DESCRIPTION
**Pull request by TobiasStockmanns**
Series of small bug fixes / features:
FairTrackParP / H: enabled to run without FairField
FairRootManager: New method InitTSBuffer to create a FairWriteoutBuffer already in the initialization stage
FairMultiLinkedData: solve a crash when a branch to insert old FairLinks is missing

### CODE REVIEW

**Comment by fuhlig1** [comment]
Hi Tobias,

Could you implement the changes in FairTrackParH and FairTrackParP as a function in FairTrackPar which is called from all the places. I think this is much better than copying the same lines of code 12 times.

Ciao

Florian

**Comment by TobiasStockmanns** [comment]
NP. I will do so.

Am 26.08.2015 um 11:30 schrieb fuhlig1 <notifications@github.com<mailto:notifications@github.com>>:


Hi Tobias,

Could you implement the changes in FairTrackParH and FairTrackParP as a function in FairTrackPar which is called from all the places. I think this is much better than copying the same lines of code 12 times.

Ciao

Florian

—
Reply to this email directly or view it on GitHub<https://github.com/FairRootGroup/FairRoot/pull/187#issuecomment-134917202>.



------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Dr. Karl Eugen Huthmacher
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,
Prof. Dr. Sebastian M. Schmidt
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

**Comment by TobiasStockmanns** [comment]
Modifications done. Please pull it into the dev branch :-)

Cheers,

Tobias

**Comment by fuhlig1** [comment]
Implemented with commit 57f1bcc.

**Pull request closed without merging**
