### PR TITLE
MQ warnings fix

### PR DESCRIPTION
**Pull request by karabowi**
Replaced CheckCurrentState by !NewStatePending.

---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by dennisklein** [comment]
https://cdash.gsi.de/buildSummary.php?buildid=226354
https://cdash.gsi.de/buildSummary.php?buildid=226353
https://cdash.gsi.de/buildSummary.php?buildid=226350
https://cdash.gsi.de/buildSummary.php?buildid=226348

Have a few failed tests. It is not obvious to me, if they are related to this PR. Please double check. One thing to note is that the tests only fail on demac016.

**Comment by karabowi** [comment]
I think that this huge number of warnings is connected to Mojave.
See f.e. https://stackoverflow.com/questions/51314888/ld-warning-text-based-stub-file-are-out-of-sync-falling-back-to-library-file/55344565 for solutions.

**Comment by dennisklein** [comment]
> I think that this huge number of warnings is connected to Mojave.

Alright, but what about the failed tests?

**Comment by dennisklein** [comment]
Ran the CI again against dev and then with this PR, and it passed as expected. Merging.

**Pull request merged**
