### PR TITLE
fix: Avoid casting to void

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
Instead of casting to void to ignore a return value, use `std::ignore`.

See: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-casts

---

Checklist:

* [X] Followed the [Contributing Guidelines](https://github.com/FairRootGroup/FairRoot/blob/dev/CONTRIBUTING.md)

### CODE REVIEW

**Review by dennisklein — DISMISSED** [review]
Do we want to add ES.48 as adopted rule in CONTRIBUTING.md as well?

**Comment by ChristianTackeGSI** [comment]
> Do we want to add ES.48 as adopted rule in CONTRIBUTING.md as well?

IMHO yes.

We (partly) already did by adopting `cppcoreguidelines-pro-type-cstyle-cast` in clang-tidy.

Should I add it to CONTRIBUTING in this PR?

**Comment by dennisklein** [comment]
> > Do we want to add ES.48 as adopted rule in CONTRIBUTING.md as well?
> 
> IMHO yes.
> 
> We (partly) already did by adopting `cppcoreguidelines-pro-type-cstyle-cast` in clang-tidy.
> 
> Should I add it to CONTRIBUTING in this PR?

As you wish, but before we merge it, let's make it a quick point on next group meeting.

**Comment by ChristianTackeGSI** [comment]
> As you wish, but before we merge it, let's make it a quick point on next group meeting.

- Left it out from this PR, so that it can "just" be merged.
- Added ES.48 to Group Meeting (can you add it to CONTRIBUTING.md, if it's approved, please?)

**Review by dennisklein — APPROVED** [review]

**Pull request merged**
