### PR TITLE
Fix segfault when closing event display.

### PR DESCRIPTION
**Pull request by DanielWielanek**
This should fix the issue 

---

Checklist:

* [x] Rebased against `dev` branch
* [ ] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [ ] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by ChristianTackeGSI** [comment]
Thanks for looking into this!

I have no experience with this part of the code at all, but I just wonder, what the removed code was actually supposed to perform? Isn't that needed any longer or was it not working anyhow?

**Comment by DanielWielanek** [comment]
Actually this code is responsible for "the tabs" that hold detector's views (3D, two projections, and 3D+ projections).
In principle I copied them from some ROOT tutorials. But now I found out, that (from uknown reason) I can create only one "tab" without segfaut. So now only one "tab" is created - for this 3 views. It seems that rest of the views doesn't require "tab" creation - it's done automatically. Maybe that's why code crash.
Unfortunatelly the ROOT documentation is very, very poor - there is even no description what some classes really do. Actually event debugger did not help mee because gdb stucks in some infinite loops.

**Comment by kresan** [comment]
Did not fix the crash in my case, still segfaulting when closing the window. I was using Rutherford example to test your modifications.
macOS 12.2.1, FairSoft apr21p2.

**Comment by DanielWielanek** [comment]
Do you mean examples/simulation/rutherford? I looked and seems to work for me (FairSoft apr21_patches from October + Linux Mint).
Did you just open and close the ED? or do some additional steps?

**Comment by kresan** [comment]
I was first clicking on the projections and then closing the window. Moreover, crash happens not always. First 2 tries were successful.
Maybe we need more crash tests, on other systems.

**Comment by ChristianTackeGSI** [comment]
@kresan Does the patch in this PR improve the crash situation at least for you? Or is it as random as without?

**Comment by kresan** [comment]
The changes in this PR do not have noticeable effect on the seg fault (as random as without) and do not break the functionality we used to have.

**Comment by ChristianTackeGSI** [comment]
I *personally* would say to merge it, because it removes seemingly unneeded code.

**Comment by kresan** [comment]
It works as expected on Ubuntu 18.04. The window can be closed without crash of ROOT. Green light from my side.

@TobiasStockmanns, do you want to test with PandaRoot or can we merge this PR?

**Review by karabowi — APPROVED** [review]

**Comment by ChristianTackeGSI** [comment]
@DanielWielanek thanks for you contribution! It took a bit longer for us to review and check some corner cases, but now it's in.

**Pull request merged**
