### PR TITLE
Use const ref TVector3

### PR DESCRIPTION
**Pull request by karabowi**
Instead of reference.

Adresses issue #891 

---

Checklist:

[*] Rebased against `dev` branch
[*] My name is in the resp. CONTRIBUTORS/AUTHORS file
[*] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by dennisklein** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ geane/FairGeanePro.h  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/FairRootGroup/FairRoot/pullRequest?prid=5326102&bid=17432099)

**Comment by fuhlig1** [comment]
Checked and worked for me.
Before

```
 FairHit bla(1, TVector3{1.0, 1.0, 1.0}, TVector3{0.,0.,0.}, 1);
ROOT_prompt_0:1:9: error: no matching constructor for initialization of 'FairHit'
FairHit bla(1, TVector3{1.0, 1.0, 1.0}, TVector3{0.,0.,0.}, 1);
        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
G__BaseDict dictionary payload:5287:5: note: candidate constructor not viable: expects an l-value for 2nd argument
    FairHit(Int_t detID, TVector3& pos, TVector3& dpos, Int_t index);
    ^
G__BaseDict dictionary payload:5277:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 4 were provided
class FairHit : public FairTimeStamp
      ^
G__BaseDict dictionary payload:5283:5: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
    FairHit();

    ^
```
After:
```
FairHit bla(1, TVector3{1.0, 1.0, 1.0}, TVector3{0.,0.,0.}, 1);
root [1] .q
```

**Comment by karabowi** [comment]
I have initially only changed the said constructor, and at least FairRoot and PandaRoot are working without any problem with the changed constructor. Only then have I changed others for consistency. 
I do not think that we do need to introduce overloading in this case.

**Comment by fuhlig1** [comment]
Ok. If the change is tested with PandaRoot I have no objections to the pull request.

**Pull request merged**
