### PR TITLE
build: Adopt all CMake policies up to 3.30

### PR DESCRIPTION
**Pull request by dennisklein**
Fix CMake error reported @ https://github.com/FairRootGroup/FairRoot/pull/1586#issuecomment-2293737064

### CODE REVIEW

**Review by ChristianTackeGSI — APPROVED** [review]

**Comment by ChristianTackeGSI** [comment]
Ooops? Looks like my approving and the auto-merge cooperated and just merged without the CI running / finishing?

Hopefully the "dev" CI will find any problems?

**Comment by dennisklein** [comment]
I enabled auto-merge and the only requirement currently is approval. We could mark the checks as required if you like (we didn't in the past as there was a high failure rate).

**Comment by ChristianTackeGSI** [comment]
Maybe we could choose a subset of tests? Some "Those really work 99.9% of the time and are a good fit"? Maybe some fedora or debian one?

**Comment by dennisklein** [comment]
Sure, just tell me which.

**Pull request merged**
