### PR TITLE
Ofi transport

### PR DESCRIPTION
**Pull request by dennisklein**
First implementation for #563 

---

| Parameter | Value |
| --- | --- |
| Channel type | PAIR |
| Channel address formats (user-facing) | `tcp://host:port`, `verbs://host:port` |
| NIC configuration | auto-detection and `--network-interface` |
| Connection mgmt / Meta data | ZeroMQ |
| ZeroMQ providers | `tcp` |
| Bulk data | OFI (`FI_MSG`, `FI_EP_RDM`) |
| OFI providers | `fi_sockets` (dev), `fi_verbs` |

```
[PAIR L][17:57:31][DEBUG] Transport: Using ZeroMQ (4.2.2) & OFI libfabric (API 1.5)
[PAIR L][17:57:31][DEBUG] Adding 'ofi' transport to the device.
```

---

`fi_getinfo` example discovery of the `lo`opback device:

```
[PAIR L][18:20:01][DEBUG] fi_info:
[PAIR L]    caps: [ FI_SHARED_AV, FI_RMA_EVENT, FI_SOURCE, FI_MSG, FI_RMA, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
[PAIR L]    mode: [  ]
[PAIR L]    addr_format: FI_SOCKADDR_IN
[PAIR L]    src_addrlen: 16
[PAIR L]    dest_addrlen: 0
[PAIR L]    src_addr: fi_sockaddr_in://127.0.0.1:0
[PAIR L]    dest_addr: (null)
[PAIR L]    handle: (null)
[PAIR L]    fi_tx_attr:
[PAIR L]        caps: [ FI_SHARED_AV, FI_RMA_EVENT, FI_SOURCE, FI_MSG, FI_RMA, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
[PAIR L]        mode: [  ]
[PAIR L]        op_flags: [ FI_TRANSMIT_COMPLETE ]
[PAIR L]        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
[PAIR L]        comp_order: [  ]
[PAIR L]        inject_size: 255
[PAIR L]        size: 368
[PAIR L]        iov_limit: 8
[PAIR L]        rma_iov_limit: 8
[PAIR L]    fi_rx_attr:
[PAIR L]        caps: [ FI_SHARED_AV, FI_RMA_EVENT, FI_SOURCE, FI_MSG, FI_RMA, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
[PAIR L]        mode: [  ]
[PAIR L]        op_flags: [  ]
[PAIR L]        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
[PAIR L]        comp_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT, FI_ORDER_DATA ]
[PAIR L]        total_buffered_recv: 67108864
[PAIR L]        size: 368
[PAIR L]        iov_limit: 8
[PAIR L]    fi_ep_attr:
[PAIR L]        type: FI_EP_MSG
[PAIR L]        protocol: FI_PROTO_SOCK_TCP
[PAIR L]        protocol_version: 1
[PAIR L]        max_msg_size: 8388608
[PAIR L]        msg_prefix_size: 0
[PAIR L]        max_order_raw_size: 8388608
[PAIR L]        max_order_war_size: 8388608
[PAIR L]        max_order_waw_size: 8388608
[PAIR L]        mem_tag_format: 0xaaaaaaaaaaaaaaaa
[PAIR L]        tx_ctx_cnt: 16
[PAIR L]        rx_ctx_cnt: 16
[PAIR L]        auth_key_size: 0
[PAIR L]    fi_domain_attr:
[PAIR L]        domain: 0x0
[PAIR L]        name: lo
[PAIR L]        threading: FI_THREAD_SAFE
[PAIR L]        control_progress: FI_PROGRESS_AUTO
[PAIR L]        data_progress: FI_PROGRESS_AUTO
[PAIR L]        resource_mgmt: FI_RM_ENABLED
[PAIR L]        av_type: FI_AV_UNSPEC
[PAIR L]        mr_mode: [  ]
[PAIR L]        mr_key_size: 8
[PAIR L]        cq_data_size: 8
[PAIR L]        cq_cnt: 32
[PAIR L]        ep_cnt: 128
[PAIR L]        tx_ctx_cnt: 16
[PAIR L]        rx_ctx_cnt: 16
[PAIR L]        max_ep_tx_ctx: 16
[PAIR L]        max_ep_rx_ctx: 16
[PAIR L]        max_ep_stx_ctx: 0
[PAIR L]        max_ep_srx_ctx: 0
[PAIR L]        cntr_cnt: 128
[PAIR L]        mr_iov_limit: 8
[PAIR L]    caps: [  ]
[PAIR L]    mode: [  ]
[PAIR L]        auth_key_size: 0
[PAIR L]        max_err_data: 0
[PAIR L]        mr_cnt: 0
[PAIR L]    fi_fabric_attr:
[PAIR L]        name: 127.0.0.0/8
[PAIR L]        prov_name: sockets
[PAIR L]        prov_version: 2.0
[PAIR L]        api_version: 1.5
[PAIR L]
```

### CODE REVIEW

**Comment by dennisklein** [comment]
@rbx 9074406 we need to solve differently. This currently breaks the nanomsg transport. I am not sure yet, how, though. It is basically the same problem, if you want to combine poll items from different transports into a single poll set.

**Comment by rbx** [comment]
The polling part in the channel is only needed for the version of the transfers that have a user-added timeout. This can be solved on transport level, but changing those for ZMQ is expensive because it requires a reconnect.
Internally in the transport i anyway set certain timeouts to keep the transport from hanging in the edge cases. What we can do is only treat the user given timeout as a multiple of the internal transport timeout (modify it if needed). This would remove the poll in the channel and also eliminate the need for the now complicated command socket mechanism.

**Comment by dennisklein** [comment]
```
# mkdir build && cd build
build# cmake -DBUILD_OFI_TRANSPORT=ON -DOFI_ROOT=/u/dklein/libfabric_install ..
build# cmake --build . --target FairMQFull -- -j4
build# bin/sink --id sink1 --transport ofi --severity debug --max-iterations 0 --channel-config name=data,type=pair,method=bind,address=verbs://10.20.1.20:12000
build# bin/bsampler --id bsampler1 --transport ofi --severity debug --msg-size 100000 --same-msg false --msg-rate 0 --max-iterations 0 --channel-config name=data,type=pair,method=connect,address=verbs://10.20.1.20:12000
```

Adapt the paths, address and port. On machines without IB, use `tcp://...`. This implementation is the first pass and not very stable, e.g. sink needs to be started before bsampler at the moment.

**Comment by dennisklein** [comment]
To run the ofi unit test:

```
build# cmake --build . --target FairMQTests -- -j4
build# bin/testsuite_FairMQ.Protocols --gtest_filter="*Ofi*"
```

**Pull request merged**
