### PR TITLE
Support Boost 1.70

### PR DESCRIPTION
**Pull request by dennisklein**
Supersedes #896 

I addressed a couple of non Boost-related CMake issues I encountered on the way.

@ktf I took the liberty to add a new commit in your name with the relevant fixups already done in #896.

This needs to be tested also with alibuild/O2, which I have not yet gotten to run through without being stopped by error on various dependencies already. @ktf which alidist *default* is supposed to work currently?

### CODE REVIEW

**Comment by ktf** [comment]
—default o2 is what i use...

--
Ciao,
Giulio

**Comment by dennisklein** [comment]
For reference:

Testing this currently with alidist, getting

```
DEBUG:O2:FairRoot:O2-1.0.0: [ 76%] Linking CXX shared library ../../lib/libMCConfigurator.so
DEBUG:O2:FairRoot:O2-1.0.0: /usr/bin/ld: cannot find -lPythia6
DEBUG:O2:FairRoot:O2-1.0.0: collect2: error: ld returned 1 exit status
DEBUG:O2:FairRoot:O2-1.0.0: gmake[2]: *** [fairtools/MCConfigurator/CMakeFiles/MCConfigurator.dir/build.make:158: lib/libMCConfigurator.so.18.2.0] Error 1
DEBUG:O2:FairRoot:O2-1.0.0: gmake[1]: *** [CMakeFiles/Makefile2:1351: fairtools/MCConfigurator/CMakeFiles/MCConfigurator.dir/all] Error 2
DEBUG:O2:FairRoot:O2-1.0.0: gmake[1]: *** Waiting for unfinished jobs....
```

This sounds familiar. I think it was fixed long ago, investigating. @fuhlig1 This looks like it should be relevant for the FairRoot 18.2 release, too?

**Comment by fuhlig1** [comment]
I think the problem is the name of the library. @dennisklein could you please check if the name in alidist is libpythia6 or libPythia6.

**Comment by dennisklein** [comment]
> I think the problem is the name of the library. @dennisklein could you please check if the name in alidist is libpythia6 or libPythia6.

I fixed it and added the commit to #899 which @MohammadAlTurany wants to include in the FairRoot 18.2 release.

This PR depends on #899, this is why it contains the same commits. It should only be merged after.

**Comment by dennisklein** [comment]
@fuhlig1 Needs another rebase once #899 is merged.

**Comment by dennisklein** [comment]
@fuhlig1 I believe the failing tests are due to tcp ports in use. Will try again later.

**Comment by dennisklein** [comment]
@ fuhlig1 Tests are green.

**Pull request merged**
