### PR TITLE
cmake/modules: fix Go execute_process recipe

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by dennisklein** [comment]
@sbinet Could you, by any chance, also address #694?

**Comment by sbinet** [comment]
assign it to me (so I don't forget about it)
but to fix it, I'll need to up my CMake game. (something I am rather reluctant to, as Go doesn't impose on me any build system :P)

**Comment by dennisklein** [comment]
Thx. Need to see how to assign you, probably you need to become a member of this repo first.

Coming back to this solution, I still have questions: What I do not understand, is the reasoning for this change. People observed build problems on gcc 4.8 platforms. Did it work there before? If I understand you correctly, you concluded, that a new cmake version behaves differently, will this change also work on other gcc platforms? So, what is the root problem people are observing on which platforms?

**Comment by sbinet** [comment]
my take on this is that the `CMakeOutput.log` and `CMakeError.log` were just red herrings.
and the `pthreadS` thing was just "normal" plumbing to detect whether on should link against `pthread` or `pthreads`.

`cmake` would fail because `go get` would either return `0` (and `FindGo` would interpret this as failure) or "not `0`" (because _e.g._ of the `GOPATH` issue) and `FindGo` would properly interpret this as failure.

AFAICT, `gcc-4.8` (or otherwise) is completely irrelevant to the issue at hand: Go binaries usually do not link against any C/C++.

**Comment by dennisklein** [comment]
> my take on this is that the CMakeOutput.log and CMakeError.log were just red herrings.
and the pthreadS thing was just "normal" plumbing to detect whether on should link against pthread or pthreads.

I agree.

> cmake would fail because go get would either return 0 (and FindGo would interpret this as failure) or "not 0" (because e.g. of the GOPATH issue) and FindGo would properly interpret this as failure.

So it was broken before?

> AFAICT, gcc-4.8 (or otherwise) is completely irrelevant to the issue at hand: Go binaries usually do not link against any C/C++.

If you look in your `go env` output, there are quite a lot of gcc related variables. So far, I don't think we understand the relationship between go and gcc, do we?

**Comment by dennisklein** [comment]
> (because e.g. of the GOPATH issue)

Which issue? On my machine (Fedora27) I can execute the listing I posted in #793 without any problems (and it is what cmake would do). My hope was we could establish on which platforms this does not work and then fix the cmake accordingly. Looking at the proposed change in this PR I am still puzzled about what has changed to before, or was it broken all along?

**Comment by sbinet** [comment]
> If you look in your go env output, there are quite a lot of gcc related variables. So far, I don't think we understand the relationship between go and gcc, do we?

yes, this is used for when somebody is using `cgo` (the Go <-> C FFI).
`sbinet-alice/fer` is pure-Go (I have implemented (a subset of) ZeroMQ in pure-Go, and nanomsg had already a pure-Go package).
so there's no C involved.

> or was it broken all along?

that's quite possible (my CMake-fu is very weak (sorry about that) so I may have borked something) but I don't think so.
the `GOPATH` issue I was hinting at was when somebody had no `$GOPATH` defined.
Going to `examples/advanced/GoTutorial/src/go-processor` and then issueing `go get`, would result in an error.
Indeed, starting with Go-1.8, when no `$GOPATH` was defined, Go would default to `$HOME/go`.
but then, running `go get` from within `go-processor` would make Go try to install the resulting binary under `$HOME/go/bin` which is a build config smell for the `go` command.

**Comment by dennisklein** [comment]
> yes, this is used for when somebody is using cgo (the Go <-> C FFI).
sbinet-alice/fer is pure-Go (I have implemented (a subset of) ZeroMQ in pure-Go, and nanomsg had already a pure-Go package).
so there's no C involved

And from a quick google search I just learned there is also `gccgo` which is a go frontend for gcc. But that is not, what is used, when issuing a `go get` AFAIK.

Still confused about the `GOPATH` behaviour, but judging purely from the cmake code, the proposed change should be fine (my first guess was it is equivalent, but you did the testing and apparently its not).

**Comment by MohammadAlTurany** [comment]
Hi,
> @MohammadAlTurany Can you verify?
Yes. This change make it works on Ubuntu 14.04 with go 10.03 and gcc 4.8 

About the discussion above, I am sure it is related to the gcc, on the same machine if I use the gcc 6.2 all works fine.

**Pull request merged**
