### PR TITLE
Fix YAML include dirs cont.

### PR DESCRIPTION
**Pull request by dennisklein**
Continuation of #909

### CODE REVIEW

**Comment by davidrohr** [comment]
This looks OK for the CMakeList, but the path is also used in `fairtools/MCConfigurator/CMakeLists.txt`, which I had to change as well in #909

**Comment by dennisklein** [comment]
> also used in fairtools/MCConfigurator/CMakeLists.txt, which I had to change as well in #909

I saw, the variable should propagate downwards. I'll double check.

**Comment by davidrohr** [comment]
OK, you are right, since you overwrite the variable it will be OK.

**Comment by dennisklein** [comment]
Hm, I don't even see your case, both my system and non-system installations have even conflicting include dirs^^

```
╭─dklein@gamma ~/projects/FairRoot ‹ruby-2.6.0› ‹davidrohr/PR2*›
╰─➤  grep YAML_CPP_INCLUDE_DIR /usr/lib64/cmake/yaml-cpp/yaml-cpp-config.cmake
set(YAML_CPP_INCLUDE_DIR "/usr/include/yaml-cpp")
╭─dklein@gamma ~/projects/FairRoot ‹ruby-2.6.0› ‹davidrohr/PR2*›
╰─➤  grep -B1 YAML_CPP_INCLUDE_DIR /home/dklein/fairsoft/dev_5b980cf/lib64/cmake/yaml-cpp/yaml-cpp-config.cmake
get_filename_component(YAML_CPP_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(YAML_CPP_INCLUDE_DIR "${YAML_CPP_CMAKE_DIR}/../../../include")
```

Since we include `<yaml-cpp/yaml.h>` the include path my system installation (Fedora 30) provides is not even effective... weird packaging...

**Comment by dennisklein** [comment]
Anyways, coming back to the `fairtools/MCConfigurator/CMakeLists.txt`, I checked the absolute path is used. Merging.

**Comment by davidrohr** [comment]
Hm, I have 0.6.2 as well. the YAML CMake Config file `/usr/lib64/cmake/yaml-cpp/yaml-cpp-config.cmake` sets
`set(YAML_CPP_INCLUDE_DIR "${YAML_CPP_CMAKE_DIR}/../../../include")`
which becomes `/usr/include` (with some [something]/../). If that is used as system include path (which happened in `fairtools/MCConfigurator/CMakeLists.txt`, it breaks the compilation.

**Pull request merged**
