### PR TITLE
Update alfa-ci

### PR DESCRIPTION
**Pull request by dennisklein**

### CODE REVIEW

**Comment by dennisklein** [comment]
@MohammadAlTurany Couple of things are broken with ROOT `6-14-08`. I am reinstalling FairSoft now with `6-12-06` to see, if it is really the ROOT version.

I see [this](https://cdash.gsi.de/viewBuildError.php?buildid=193975) (on Mac), some xrootd patches are failing and finally, g4py does not compile (last two on Linux).

**Comment by dennisklein** [comment]
Ok, only Linux MT is broken, Mac works as before. Should I disable Linux MT build for now?

**Comment by dennisklein** [comment]
Actually merging to unblock ongoing PRs.

**Comment by MohammadAlTurany** [comment]
No, do not disable it I am re-compiling the MT now!

**Pull request merged**
