### PR TITLE
Always have access to FairMQProgOptions from device

### PR DESCRIPTION
**Pull request by rbx**
- Create FairMQProgOptions within a device if it has been started without access to one.
- Test devices without supplied config & two in a process.

### CODE REVIEW

**Comment by dennisklein** [comment]
Do you plan to add the `TestReceiver.cxx` and `TestSender.cxx` to the helper binary too? If not, I would move the files just inside the `fairmq/test/device` folder since they would not be related to the helper.

**Comment by dennisklein** [comment]
And we should really rename the `.cxx` files to `.h`. I messed this up in the helper.

**Comment by rbx** [comment]
yeah, i'll move to `fairmq/test/device`, will be cleaner that way.

**Comment by rbx** [comment]
Moved the test devices.

And trying if changing `std::async(...)` to `std::async(std::launch::async, ...)` helps with the failing tests.

**Pull request merged**
