### PR TITLE
add compiler check to exclude wrong error for the same symlinks: g++ c++

### PR DESCRIPTION
**Pull request by kgertsenberger**
the incorrect error "different compilers" has been encountered Ubuntu 17.10, 17.04, SLC 6... where OS has symlink c++ pointed to g++

### CODE REVIEW

**Comment by dennisklein** [comment]
CMake seems to offer a portable `diff` with `cmake -E compare_files file1 file2`. If it works, it might be preferrable even.

**Comment by kgertsenberger** [comment]
Ok, i will try this portable solution.

вт, 24 апр. 2018 г., 16:41 Dennis Klein <notifications@github.com>:

**Comment by dennisklein** [comment]
> Ok, i will try this portable solution.

@kgertsenberger Just don't spend too much time on it ;) I believe, we would also be happy to merge your proposed solution with `diff`.

**Comment by kgertsenberger** [comment]
Unfortunately, i have no MacOS, so i tested it only on Linux. 
It is not problem for me to test different solutions especially if it is maximally portable.
Thank you for your suggestion.

**Comment by MohammadAlTurany** [comment]
No problem, we have enough MACs to test it, just send the PR and it will be tested on MAC.

**Pull request closed without merging**
