### PR TITLE
Fixes to compile on MacOSX

### PR DESCRIPTION
**Pull request by ktf**
Various issues spotted while compiling FairRoot on Mac.

### CODE REVIEW

**Comment by ktf** [comment]
Any news on this?

**Comment by fuhlig1** [comment]
Sorry for the late response but due to the vacation time your request stuck in the queue. 
I correct the FindZeroMQ.cmake macro and the main CMakeLists.txt in the dev branch of FairRoot with commit 8fbc178754f4f61c93f08639888d5ac92be1e2d6 and the c++11 check with commit a3c380e8999db7c2bf8ac0c7576d934957e92509

**Comment by ktf** [comment]
Cool thanks. Any chance you have commit rights also for https://github.com/AliceO2Group/AliceO2 . I've also AliceO2Group/AliceO2#67 in the pipes since a while.

**Comment by fuhlig1** [comment]
Hi Giulio,

Am 09.09.2015 um 15:49 schrieb Giulio Eulisse <notifications@github.com>:

> Cool thanks. Any chance you have commit rights also for https://github.com/AliceO2Group/AliceO2 . I've also AliceO2Group/AliceO2#67 in the pipes since a while.

Unfortunately not.

Ciao

Florian

**Comment by ktf** [comment]
No worries, thanks.

**Pull request closed without merging**
