### PR TITLE
Corrected PROTOBUF conditional built of Tutorial3

### PR DESCRIPTION
**Pull request by matthiasrichter**
now its correctly only affecting Tutorial3

### CODE REVIEW

**Comment by fuhlig1** [comment]
Merged with branch RC_v-16.06 at commit 0f2f040.

**Comment by matthiasrichter** [comment]
Hi, is there a reason why it should not go into the dev branch as well? 
Ciao Matthias

**Comment by fuhlig1** [comment]
It will when the release is done. It would be good if you could use the RC_v-16.06 branch for the time being and test if everything is working as expected.

Ciao

Florian



Am 21.06.2016 um 09:27 schrieb Matthias Richter <notifications@github.com<mailto:notifications@github.com>>:


Hi, is there a reason why it should not go into the dev branch as well?
Ciao Matthias

**Comment by matthiasrichter** [comment]
ok, will do

**Pull request closed without merging**
