### PR TITLE
Modernize cmake, phase one

### PR DESCRIPTION
**Pull request by rbx**
- [x] Use target properties
- [x] Use exported targets of dependencies (all besides ROOT)
- [x] Adapt dictionary generator from O2
- [x] Use defaults for EXECUTABLE_OUTPUT_PATH (instead of /bin)
- [x] Fix unreachable targets: MCConfigurator and GConfig
- [x] Cleanup includes
- [x] Cleanup dependencies
- [x] Generate headers list from sources list
- [x] a bunch of random formatting changes...
- [x] Test with experiments to see what breaks (ideally nothing should)

### CODE REVIEW

**Comment by dennisklein** [comment]
I compared the install directories before and after this PR:

```diff
diff --git a/devtree2 b/rbxtree2
index f15890a20..11401afea 100644
--- a/devtree2
+++ b/rbxtree2
@@ -134,6 +134,11 @@
 ./include/FairModule.h
 ./include/FairMonitor.h
 ./include/FairMQChunkMerger.h
+./include/FairMQExHistoCanvasDrawerExample.h
+./include/FairMQExHistoCanvasDrawer.h
+./include/FairMQExHistoDevice.h
+./include/FairMQExHistoServer.h
+./include/FairMQExParamsClient.h
 ./include/FairMQExParamsContFact.h
 ./include/FairMQExParamsParOne.h
 ./include/FairMQFileSource.h
@@ -141,16 +146,13 @@
 ./include/FairMQPixAltFileSinkBin.h
 ./include/FairMQPixAltSamplerBin.h
 ./include/FairMQPixAltTaskProcessorBin.h
-./include/FairMQPixAltTaskProcessorBin.tpl
 ./include/FairMQPixelFileSinkBin.h
 ./include/FairMQPixelFileSink.h
 ./include/FairMQPixelMerger.h
 ./include/FairMQPixelSamplerBin.h
 ./include/FairMQPixelSampler.h
 ./include/FairMQPixelTaskProcessorBin.h
-./include/FairMQPixelTaskProcessorBin.tpl
 ./include/FairMQPixelTaskProcessor.h
-./include/FairMQPixelTaskProcessor.tpl
 ./include/FairMQPrimaryGeneratorDevice.h
 ./include/FairMQProcessor.h
 ./include/FairMQProcessorTask.h
@@ -264,14 +266,12 @@
 ./include/FairUnpack.h
 ./include/FairUrqmdGenerator.h
 ./include/FairVersion.h
+./include/FairVMCConfig.h
 ./include/FairVolume.h
 ./include/FairVolumeList.h
 ./include/FairWriteoutBuffer.h
 ./include/FairXMLNode.h
-./include/f_evt.h
-./include/fLmd.h
-./include/f_stccomm.h
-./include/f_ut_utime.h
+./include/FairYamlVMCConfig.h
 ./include/IOPolicy.h
 ./include/MRevBuffer.h
 ./include/MyDigi.h
@@ -496,6 +506,7 @@
 ./share/fairbase/cmake/modules/CheckCXX11Features.cmake
 ./share/fairbase/cmake/modules/CheckFortran.cmake
 ./share/fairbase/cmake/modules/FairMacros.cmake
+./share/fairbase/cmake/modules/FairRootTargetRootDictionary.cmake
 ./share/fairbase/cmake/modules/FindFairRoot.cmake
 ./share/fairbase/cmake/modules/FindGo.cmake
 ./share/fairbase/cmake/modules/FindGSL.cmake
@@ -528,15 +539,9 @@
 ./share/fairbase/examples
 ./share/fairbase/examples/advanced
 ./share/fairbase/examples/advanced/MbsTutorial
-./share/fairbase/examples/advanced/MbsTutorial/data
-./share/fairbase/examples/advanced/MbsTutorial/data/sample_data_2.lmd
-./share/fairbase/examples/advanced/MbsTutorial/macros
-./share/fairbase/examples/advanced/MbsTutorial/macros/unpack_mbs.C
+./share/fairbase/examples/advanced/MbsTutorial/sample_data_2.lmd
+./share/fairbase/examples/advanced/MbsTutorial/unpack_mbs.C
 ./share/fairbase/examples/advanced/Tutorial3
-./share/fairbase/examples/advanced/Tutorial3/bin
-./share/fairbase/examples/advanced/Tutorial3/bin/tut3-processor
-./share/fairbase/examples/advanced/Tutorial3/bin/tut3-sampler
-./share/fairbase/examples/advanced/Tutorial3/bin/tut3-sink
 ./share/fairbase/examples/advanced/Tutorial3/eventDisplay.C
 ./share/fairbase/examples/advanced/Tutorial3/macro
 ./share/fairbase/examples/advanced/Tutorial3/macro/data
@@ -593,11 +598,14 @@
 ./share/fairbase/examples/MQ/parameters
 ./share/fairbase/examples/MQ/parameters/bin
 ./share/fairbase/examples/MQ/parameters/bin/ex-params-client
+./share/fairbase/examples/MQ/parameters/bin/tut3-processor
+./share/fairbase/examples/MQ/parameters/bin/tut3-sampler
+./share/fairbase/examples/MQ/parameters/bin/tut3-sink
 ./share/fairbase/examples/MQ/pixelAlternative
 ./share/fairbase/examples/MQ/pixelAlternative/bin
-./share/fairbase/examples/MQ/pixelAlternative/bin/pixalt-processorBin
-./share/fairbase/examples/MQ/pixelAlternative/bin/pixalt-samplerBin
-./share/fairbase/examples/MQ/pixelAlternative/bin/pixalt-sinkBin
+./share/fairbase/examples/MQ/pixelAlternative/bin/pixalt-processor-bin
+./share/fairbase/examples/MQ/pixelAlternative/bin/pixalt-sampler-bin
+./share/fairbase/examples/MQ/pixelAlternative/bin/pixalt-sink-bin
 ./share/fairbase/examples/MQ/pixelAlternative/bin/startFairMQPixAlt.sh
 ./share/fairbase/examples/MQ/pixelDetector
 ./share/fairbase/examples/MQ/pixelDetector/bin
@@ -607,13 +615,13 @@
 ./share/fairbase/examples/MQ/pixelDetector/bin/pixel-dds-topology.xml
 ./share/fairbase/examples/MQ/pixelDetector/bin/pixel-merger
 ./share/fairbase/examples/MQ/pixelDetector/bin/pixel-processor
-./share/fairbase/examples/MQ/pixelDetector/bin/pixel-processorBin
+./share/fairbase/examples/MQ/pixelDetector/bin/pixel-processor-bin
 ./share/fairbase/examples/MQ/pixelDetector/bin/pixel-sampler
-./share/fairbase/examples/MQ/pixelDetector/bin/pixel-samplerBin
+./share/fairbase/examples/MQ/pixelDetector/bin/pixel-sampler-bin
+./share/fairbase/examples/MQ/pixelDetector/bin/pixel-sim
 ./share/fairbase/examples/MQ/pixelDetector/bin/pixel-sink
-./share/fairbase/examples/MQ/pixelDetector/bin/pixel-sinkBin
+./share/fairbase/examples/MQ/pixelDetector/bin/pixel-sink-bin
 ./share/fairbase/examples/MQ/pixelDetector/bin/run_pixel_dds_chain.sh
-./share/fairbase/examples/MQ/pixelDetector/bin/run-sim
 ./share/fairbase/examples/MQ/pixelDetector/bin/startFairMQPixel_3Levels.sh
 ./share/fairbase/examples/MQ/pixelDetector/bin/startFairMQPixelBinProxy.sh
 ./share/fairbase/examples/MQ/pixelDetector/bin/startFairMQPixelBin.sh
@@ -633,9 +641,9 @@
 ./share/fairbase/examples/MQ/pixelDetector/param/pixel_digi.par
 ./share/fairbase/examples/MQ/pixelSimSplit
 ./share/fairbase/examples/MQ/pixelSimSplit/bin
-./share/fairbase/examples/MQ/pixelSimSplit/bin/runMQChMer
-./share/fairbase/examples/MQ/pixelSimSplit/bin/runMQGen
-./share/fairbase/examples/MQ/pixelSimSplit/bin/runMQTrans
+./share/fairbase/examples/MQ/pixelSimSplit/bin/pixel-sim-chunk-merger
+./share/fairbase/examples/MQ/pixelSimSplit/bin/pixel-sim-gen
+./share/fairbase/examples/MQ/pixelSimSplit/bin/pixel-sim-transport
 ./share/fairbase/examples/MQ/serialization
 ./share/fairbase/examples/MQ/serialization/bin
 ./share/fairbase/examples/MQ/serialization/bin/ex-serialization1-processor
@@ -652,7 +660,7 @@
 ./share/fairbase/examples/simulation/rutherford/run_rutherford.C
 ./share/fairbase/examples/simulation/Tutorial1
 ./share/fairbase/examples/simulation/Tutorial1/bin
-./share/fairbase/examples/simulation/Tutorial1/bin/runTutorial1
+./share/fairbase/examples/simulation/Tutorial1/bin/tutorial1
 ./share/fairbase/examples/simulation/Tutorial1/run_tutorial1.C
 ./share/fairbase/examples/simulation/Tutorial1/run_tutorial1_mesh.C
 ./share/fairbase/examples/simulation/Tutorial1/run_tutorial1_pythia6.C
@@ -664,9 +672,8 @@
 ./share/fairbase/examples/simulation/Tutorial2/parameters
 ./share/fairbase/examples/simulation/Tutorial2/parameters/tutdet.digi.par
 ./share/fairbase/examples/simulation/Tutorial2/read_digis.C
-./share/fairbase/examples/simulation/Tutorial2/run_bg.C
-./share/fairbase/examples/simulation/Tutorial2/run_sg1.C
-./share/fairbase/examples/simulation/Tutorial2/run_sg.C
+./share/fairbase/examples/simulation/Tutorial2/run_background.C
+./share/fairbase/examples/simulation/Tutorial2/run_signal.C
 ./share/fairbase/examples/simulation/Tutorial2/run_tutorial2.C
 ./share/fairbase/examples/simulation/Tutorial4
 ./share/fairbase/examples/simulation/Tutorial4/analysis
```

Some look like renames, but not all?

**Comment by dennisklein** [comment]
The `lib` dir is now `lib64` on my platform, this is intended, otherwise the diff is here

```diff
diff --git a/devlibtree2 b/rbxlibtree2
index f8e8621ca..4b5dc06fe 100644
--- a/devlibtree2
+++ b/rbxlibtree2
@@ -1,141 +1,151 @@
 .
-./G__BaseDict_rdict.pcm
-./G__EventDisplayDict_rdict.pcm
-./G__ExLmdDict_rdict.pcm
-./G__FairDataMatchDict_rdict.pcm
-./G__FairFastSimDict_rdict.pcm
-./G__FairMQExHistogramServerDict_rdict.pcm
-./G__FairMQExParametersDict_rdict.pcm
-./G__FairRutherfordDict_rdict.pcm
-./G__FairTestDetectorDict_rdict.pcm
-./G__FairToolsDict_rdict.pcm
-./G__GeaneDict_rdict.pcm
-./G__GenDict_rdict.pcm
-./G__GeoBaseDict_rdict.pcm
-./G__MbsTutorialDict_rdict.pcm
-./G__MCStackDict_rdict.pcm
-./G__ParBaseDict_rdict.pcm
-./G__PassiveDict_rdict.pcm
-./G__PixelAltDict_rdict.pcm
-./G__PixelDict_rdict.pcm
-./G__SerializationExampleDict_rdict.pcm
-./G__SimMQDict_rdict.pcm
-./G__TrkBaseDict_rdict.pcm
-./G__Tutorial1Dict_rdict.pcm
-./G__Tutorial2Dict_rdict.pcm
-./G__Tutorial4Dict_rdict.pcm
+./G__Base_rdict.pcm
+./G__EventDisplay_rdict.pcm
+./G__ExHistogramServer_rdict.pcm
+./G__ExLmd_rdict.pcm
+./G__ExParameters_rdict.pcm
+./G__ExSerialization_rdict.pcm
+./G__FairDataMatch_rdict.pcm
+./G__FairFastSim_rdict.pcm
+./G__FairRutherford_rdict.pcm
+./G__FairTestDetector_rdict.pcm
+./G__FairTools_rdict.pcm
+./G__GConfig_rdict.pcm
+./G__Geane_rdict.pcm
+./G__Gen_rdict.pcm
+./G__GeoBase_rdict.pcm
+./G__MbsTutorial_rdict.pcm
+./G__MCConfigurator_rdict.pcm
+./G__MCStack_rdict.pcm
+./G__ParBase_rdict.pcm
+./G__Passive_rdict.pcm
+./G__PixelAlt_rdict.pcm
+./G__Pixel_rdict.pcm
+./G__SimMQ_rdict.pcm
+./G__TrkBase_rdict.pcm
+./G__Tutorial1_rdict.pcm
+./G__Tutorial2_rdict.pcm
+./G__Tutorial4_rdict.pcm
 ./libAlignment.so
-./libAlignment.so.18
+./libAlignment.so.18.2
 ./libAlignment.so.18.2.0
 ./libBaseMQ.so
-./libBaseMQ.so.18
+./libBaseMQ.so.18.2
 ./libBaseMQ.so.18.2.0
 ./libBase.rootmap
 ./libBase.so
-./libBase.so.18
+./libBase.so.18.2
 ./libBase.so.18.2.0
 ./libEventDisplay.rootmap
 ./libEventDisplay.so
-./libEventDisplay.so.18
+./libEventDisplay.so.18.2
 ./libEventDisplay.so.18.2.0
+./libExHistogramServer.rootmap
+./libExHistogramServer.so
+./libExHistogramServer.so.18.2
+./libExHistogramServer.so.18.2.0
 ./libExLmd.rootmap
 ./libExLmd.so
-./libExLmd.so.18
+./libExLmd.so.18.2
 ./libExLmd.so.18.2.0
+./libExParameters.rootmap
+./libExParameters.so
+./libExParameters.so.18.2
+./libExParameters.so.18.2.0
+./libExSerialization.rootmap
+./libExSerialization.so
+./libExSerialization.so.18.2
+./libExSerialization.so.18.2.0
 ./libFairDataMatch.rootmap
 ./libFairDataMatch.so
-./libFairDataMatch.so.18
+./libFairDataMatch.so.18.2
 ./libFairDataMatch.so.18.2.0
 ./libFairFastSim.rootmap
 ./libFairFastSim.so
-./libFairFastSim.so.18
+./libFairFastSim.so.18.2
 ./libFairFastSim.so.18.2.0
 ./libFairMCStepLogger.so
-./libFairMCStepLogger.so.18
+./libFairMCStepLogger.so.18.2
 ./libFairMCStepLogger.so.18.2.0
-./libFairMQExHistogramServer.rootmap
-./libFairMQExHistogramServer.so
-./libFairMQExHistogramServer.so.18
-./libFairMQExHistogramServer.so.18.2.0
-./libFairMQExParameters.rootmap
-./libFairMQExParameters.so
-./libFairMQExParameters.so.18
-./libFairMQExParameters.so.18.2.0
 ./libFairRutherford.rootmap
 ./libFairRutherford.so
-./libFairRutherford.so.18
+./libFairRutherford.so.18.2
 ./libFairRutherford.so.18.2.0
 ./libFairTestDetector.rootmap
 ./libFairTestDetector.so
-./libFairTestDetector.so.18
+./libFairTestDetector.so.18.2
 ./libFairTestDetector.so.18.2.0
 ./libFairTools.rootmap
 ./libFairTools.so
-./libFairTools.so.18
+./libFairTools.so.18.2
 ./libFairTools.so.18.2.0
+./libGConfig.rootmap
+./libGConfig.so
+./libGConfig.so.18.2
+./libGConfig.so.18.2.0
 ./libGeane.rootmap
 ./libGeane.so
-./libGeane.so.18
+./libGeane.so.18.2
 ./libGeane.so.18.2.0
 ./libGen.rootmap
 ./libGen.so
-./libGen.so.18
+./libGen.so.18.2
 ./libGen.so.18.2.0
 ./libGeoBase.rootmap
 ./libGeoBase.so
-./libGeoBase.so.18
+./libGeoBase.so.18.2
 ./libGeoBase.so.18.2.0
 ./libMbsAPI.so
-./libMbsAPI.so.18
+./libMbsAPI.so.18.2
 ./libMbsAPI.so.18.2.0
 ./libMbsTutorial.rootmap
 ./libMbsTutorial.so
-./libMbsTutorial.so.18
+./libMbsTutorial.so.18.2
 ./libMbsTutorial.so.18.2.0
+./libMCConfigurator.rootmap
+./libMCConfigurator.so
+./libMCConfigurator.so.18.2
+./libMCConfigurator.so.18.2.0
 ./libMCStack.rootmap
 ./libMCStack.so
-./libMCStack.so.18
+./libMCStack.so.18.2
 ./libMCStack.so.18.2.0
 ./libParBase.rootmap
 ./libParBase.so
-./libParBase.so.18
+./libParBase.so.18.2
 ./libParBase.so.18.2.0
 ./libParMQ.so
-./libParMQ.so.18
+./libParMQ.so.18.2
 ./libParMQ.so.18.2.0
 ./libPassive.rootmap
 ./libPassive.so
-./libPassive.so.18
+./libPassive.so.18.2
 ./libPassive.so.18.2.0
 ./libPixelAlt.rootmap
 ./libPixelAlt.so
-./libPixelAlt.so.18
+./libPixelAlt.so.18.2
 ./libPixelAlt.so.18.2.0
 ./libPixel.rootmap
 ./libPixel.so
-./libPixel.so.18
+./libPixel.so.18.2
 ./libPixel.so.18.2.0
-./libSerializationExample.rootmap
-./libSerializationExample.so
-./libSerializationExample.so.18
-./libSerializationExample.so.18.2.0
 ./libSimMQ.rootmap
 ./libSimMQ.so
-./libSimMQ.so.18
+./libSimMQ.so.18.2
 ./libSimMQ.so.18.2.0
 ./libTrkBase.rootmap
 ./libTrkBase.so
-./libTrkBase.so.18
+./libTrkBase.so.18.2
 ./libTrkBase.so.18.2.0
 ./libTutorial1.rootmap
 ./libTutorial1.so
-./libTutorial1.so.18
+./libTutorial1.so.18.2
 ./libTutorial1.so.18.2.0
 ./libTutorial2.rootmap
 ./libTutorial2.so
-./libTutorial2.so.18
+./libTutorial2.so.18.2
 ./libTutorial2.so.18.2.0
 ./libTutorial4.rootmap
 ./libTutorial4.so
-./libTutorial4.so.18
+./libTutorial4.so.18.2
 ./libTutorial4.so.18.2.0
```

Looks good I would say.

**Comment by dennisklein** [comment]
```diff
diff --git a/install2/lib/libBase.rootmap b/install1/lib64/libBase.rootmap
index 720c19d4a..e3820690a 100644
--- a/install2/lib/libBase.rootmap
+++ b/install1/lib64/libBase.rootmap
@@ -1,4 +1,4 @@
-[ Base.so ]
+[ libBase.so.18.2.0 ]
 # List of selected classes
 class FairAnaSelector
 class FairBaseContFact
@@ -69,20 +69,17 @@ class FairVolumeList
 class FairWriteoutBuffer
 class MRevBuffer
 class REvent
-header FairFileSource.h
-header FairIon.h
 header FairLink.h
-header FairMCApplication.h
 header FairMbsSource.h
 header FairModule.h
 header FairMultiLinkedData.h
 header FairMultiLinkedData_Interface.h
-header FairParticle.h
 header FairRecoEventHeader.h
 header FairRootManager.h
-header FairRunInfo.h
+header FairRun.h
 header FairSink.h
 header FairSource.h
 header FairTask.h
 header FairTimeStamp.h
 header FairUnpack.h
+header FairWriteoutBuffer.h
```

**Comment by rbx** [comment]
> I compared the install directories before and after this PR:
> ...
> Some look like renames, but not all?

Checked and fixed the missing headers.

> The `lib` dir is now `lib64` on my platform, this is intended, otherwise the diff is here
> ...
> Looks good I would say.

Looks correct to me too. The two missing ones are result of unreachable targets in dev branch.

**Comment by rbx** [comment]
I tested this with R3BRoot and with PandaRoot.
As expected in both cases there are some minor breaks because of missing include statements on their side. But besides that everything seemed to work fine.

I submitted PRs to both with changes required on their side:
[PandaRoot MR](https://git.panda.gsi.de/PandaRootGroup/PandaRoot/merge_requests/164)
[R3BRoot PR](https://github.com/R3BRootGroup/R3BRoot/pull/285)
(In case of R3BRoot there is one more thing as you can see, but it is actually not related to this PR, but to an older commit in our dev that removes `FairRootCmakePolicies`).

**Comment by rbx** [comment]
Also tested with cbmroot now. As expected there are several missing include statements.
I submitted a fix to Florian. With the fix compilation and tests are green.

Waiting for Florian to also reproduce it.

**Pull request merged**
