### PR TITLE
Valid json files

### PR DESCRIPTION
**Pull request by sbinet**
Use strict(er) and more regular JSON schema.

Addresses #444

### CODE REVIEW

**Comment by sbinet** [comment]
I can squash the 2 commits if needed.
(I didn't squash them yet b/c I wasn't sure the `fairmq/options` one was intentionnally written as such)

**Comment by sbinet** [comment]
BTW, this exercize in being stricter uncovered this bug:
`./examples/MQ/9-PixelDetector/run/options/Pixel9MQConfig_2Samplers.json`

```json
            "id": "processor7",
            "channel":
            [{
```
(around line 226)

I can add another commit with the `JSON` formatter I was talking about in #444.

**Comment by rbx** [comment]
Yes please. Thank you!

**Comment by sbinet** [comment]
done

**Pull request merged**
